Proves that eigenvectors are orthogonal for a symmetric matrix

In [189]:
import numpy as np

In [190]:
def mat_mul(A, v):
    """
    This function helps us to multipy two given matirces
    """
    r1,c1 = A.shape
    r2, c2 = v.shape
    assert(c1==r2), "The matrix size has to match"
    
    # Creates a empty matrix of size r1*c2
    res = np.zeros((r1, c2))
    
    # Iterates over every row and every column of A and v matrices respectively
    for i in range(r1):
        for j in range(c2):
            for k in range(c1):
                res[i][j] += A[i][k]*v[k][j]
    return(res)  

In [191]:
def det (A):
    """
    Computes the determinant of a 2*2 or 3*3 square matrix
    """
    r, c = A.shape
    assert(r == c), "Matrix has to be square"
    det = 0
    if (r == 2):
        return(A[0][0]*A[1][1] - A[0][1]*A[1][0])
    
    for i in range(r):
        minor1 = 1
        minor2 = 1
        for j in range (c):
            minor1 *= A[j][(j+i)%r]
            minor2 *= A[r-j-1][(j+i)%r]   
        det += (minor1-minor2)
    return(det)

In [192]:
def inv(A):
    """
    Calculates the Inverse of a matrix if it exists
    """
    r, c = A.shape
    assert (r==c), "Matrix has to be square"
    assert(det(A) != 0), "Matrix has to be non-singular"
    
    # Creating an augumented matrix
    augumentedMatrix = np.zeros((r, c*2))
    
    for i in range(r):
        for j in range(c):
            augumentedMatrix[i][j] = A[i][j]
        augumentedMatrix[i][j+i+1] = 1
        
    # Changes the row which haves a diagonal element zero
    for i in range(r):
        if augumentedMatrix[i][i] == 0:
            augumentedMatrix[i], augumentedMatrix[(i + 1) % r] = np.copy(augumentedMatrix[(i + 1) % r]), np.copy(augumentedMatrix[i])
    
    # Applying Gauss Jordan method to find the inverse
    for i in range(r):
        k = i
        k_count = 0
        while (k_count<r):
            if (i==k and augumentedMatrix[i][i] != 0):
                div = augumentedMatrix[i][i]
                for j in range(2*c):
                    augumentedMatrix[i][j] = augumentedMatrix[i][j]/div
            else:
                mul = augumentedMatrix[k][i]
                for j in range(2*c):
                    augumentedMatrix[k][j] -= (mul*augumentedMatrix[i][j]) 
            k_count += 1
            k = (k+1)%r
    
    # Seperates the inverse from the augumented matrix
    res = augumentedMatrix[:, c:]
    return(res)

In [193]:
A = np.array([[6, -2, -1],
             [-2, 6, -1],
             [-1, -1, 5]])
dim = len(A)
eig_val, eig_vec = np.linalg.eig(A)

# Converts the eigen vector into an unit vector
nor = [0]*dim
for i in range(dim):
    for j in range(dim):
        nor[j] += (eig_vec[i][j]**2)

P = np.zeros((dim, dim))
for i in range(dim):
    for j in range(dim):
        P[i][j] = eig_vec[i][j]/(nor[j]**0.5)
        
# Computes a matrix D with diagonal values as eigen values
D = np.zeros((dim, dim))
for i in range(dim):
    D[i][i] = eig_val[i]

# Computes the P transpose
P_tran = np.zeros((dim, dim))
for i in range(dim):
    for j in range(dim):
        P_tran[i][j] = P[j][i]
        
one = mat_mul(P, mat_mul(D, P_tran))   # PDP^T

P_inv = inv(P)
two = mat_mul(P, mat_mul(D, P_inv))   # PDP^-1

In [194]:
A

array([[ 6, -2, -1],
       [-2,  6, -1],
       [-1, -1,  5]])

In [195]:
one

array([[ 6., -2., -1.],
       [-2.,  6., -1.],
       [-1., -1.,  5.]])

In [196]:
two

array([[ 6., -2., -1.],
       [-2.,  6., -1.],
       [-1., -1.,  5.]])

Thus, A = PDP^T = PDP^-1.
i.e., P is a orthogonal matrix
=> Eigen vectors are orthogonal